language: go
go: 1.7.1
before_install:
  - export PATH=$HOME/gopath/bin:$PATH
  - go get github.com/tools/godep
  - go get github.com/boltdb/bolt/cmd/bolt
  - mkdir local
script: godep go test -v ./...
sudo: false
